[2024-03-09 00:42:25,798: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 00:42:25,799: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "E:\ML Project\COVID project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "E:\ML Project\COVID project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\config\configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\utils\common.py", line 37, in read_yaml
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\utils\common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
