[2024-01-26 22:22:56,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-26 22:22:56,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: created directory at: artifacts]
[2024-01-26 22:22:56,877: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-26 22:22:56,878: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:04,099: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:05,285: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:27:38,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:27:38,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:27:38,369: INFO: common: created directory at: artifacts]
[2024-01-27 19:27:38,371: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:30:47,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:30:47,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:30:47,740: INFO: common: created directory at: artifacts]
[2024-01-27 19:30:47,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:31:38,242: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:41:40,071: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:41:40,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:41:40,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:41:40,078: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:29,771: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:30,324: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:44:08,865: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:44:08,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: created directory at: artifacts]
[2024-01-27 19:44:08,871: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:44:08,871: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:08,879: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:45:09,446: INFO: main: *******************]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 19:45:09,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:45:09,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:45:09,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:45:10,110: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:18:18,296: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:18:18,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:18:18,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:18:18,318: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:20,786: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:21,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:19:21,328: INFO: main: *******************]
[2024-01-27 20:19:21,328: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:19:21,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:19:21,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:19:21,334: INFO: common: created directory at: artifacts]
[2024-01-27 20:19:21,335: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:19:21,807: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:19:22,131: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:20:40,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:20:40,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:20:40,837: INFO: common: created directory at: artifacts]
[2024-01-27 20:20:40,839: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:23:11,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:23:11,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:23:11,834: INFO: common: created directory at: artifacts]
[2024-01-27 20:23:11,836: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:41:43,007: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:41:43,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:41:43,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:41:43,015: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:20,655: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:21,291: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:43:21,292: INFO: main: *******************]
[2024-01-27 20:43:21,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:43:21,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:21,298: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:43:21,745: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:43:22,206: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:43:22,207: INFO: main: *******************]
[2024-01-27 20:43:22,207: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:43:22,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:22,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:22,213: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:22,214: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:43:22,214: ERROR: main: "'ConfigBox' object has no attribute 'epochs'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'epochs'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 33, in <module>
    model_trainer.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\config\configuration.py", line 66, in get_training_config
    params_epochs=params.EPOCHS,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'epochs'"
[2024-01-27 20:45:14,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:45:14,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:45:14,596: INFO: common: created directory at: artifacts]
[2024-01-27 20:45:14,597: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:46:27,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:46:27,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:46:27,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:46:27,101: INFO: common: created directory at: artifacts]
[2024-01-27 20:46:27,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:46:27,103: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:00,945: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:01,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:48:01,577: INFO: main: *******************]
[2024-01-27 20:48:01,578: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:48:01,580: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:01,583: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:48:02,086: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:48:02,377: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:48:02,378: INFO: main: *******************]
[2024-01-27 20:48:02,378: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:48:02,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:02,384: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:02,385: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:02,386: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:48:39,543: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-08 22:57:57,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 22:57:57,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 22:57:57,853: INFO: common: created directory at: artifacts]
[2024-02-08 22:58:17,466: INFO: common: json file saved at: scores.json]
[2024-02-08 22:58:28,258: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-08 22:58:29,842: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpouszrem3\model\data\model\assets]
[2024-02-08 23:02:00,819: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/95841584265043d1baabf1dcf05389f0/41070d4228a0474cbe4853a586caa5fb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-08 23:07:39,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:07:39,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:07:39,432: INFO: common: created directory at: artifacts]
[2024-02-08 23:07:57,806: INFO: common: json file saved at: scores.json]
[2024-02-08 23:08:19,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:08:19,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:08:19,618: INFO: common: created directory at: artifacts]
[2024-02-08 23:08:37,887: INFO: common: json file saved at: scores.json]
[2024-02-08 23:09:14,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:09:14,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:09:14,853: INFO: common: created directory at: artifacts]
[2024-02-08 23:09:33,888: INFO: common: json file saved at: scores.json]
[2024-02-08 23:11:42,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:11:42,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:11:42,957: INFO: common: created directory at: artifacts]
[2024-02-08 23:12:02,071: INFO: common: json file saved at: scores.json]
[2024-02-08 23:12:02,224: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow/runs/create]
[2024-02-08 23:13:23,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:13:23,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:13:23,718: INFO: common: created directory at: artifacts]
[2024-02-08 23:13:42,966: INFO: common: json file saved at: scores.json]
[2024-02-09 00:53:52,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 00:53:52,878: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 00:53:52,881: INFO: common: created directory at: artifacts]
[2024-02-09 00:54:11,859: INFO: common: json file saved at: scores.json]
[2024-02-09 11:13:58,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:13:58,256: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:13:58,259: INFO: common: created directory at: artifacts]
[2024-02-09 11:14:17,423: INFO: common: json file saved at: scores.json]
[2024-02-09 11:17:39,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:17:39,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:17:39,171: INFO: common: created directory at: artifacts]
[2024-02-09 11:17:57,530: INFO: common: json file saved at: scores.json]
[2024-02-09 11:27:31,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:27:31,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:27:31,585: INFO: common: created directory at: artifacts]
[2024-02-09 11:27:49,751: INFO: common: json file saved at: scores.json]
[2024-02-09 11:47:48,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:47:48,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:47:48,699: INFO: common: created directory at: artifacts]
[2024-02-09 11:48:07,276: INFO: common: json file saved at: scores.json]
[2024-02-09 20:47:58,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 20:47:58,921: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 20:47:58,924: INFO: common: created directory at: artifacts]
[2024-02-09 20:48:19,757: INFO: common: json file saved at: scores.json]
[2024-02-09 21:08:45,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:08:45,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:08:45,813: INFO: common: created directory at: artifacts]
[2024-02-09 21:09:01,021: INFO: common: json file saved at: scores.json]
[2024-02-09 21:09:05,770: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:09:06,583: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmp9ins6pol\model\data\model\assets]
[2024-02-09 21:10:42,423: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:13:51,097: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:14:30,243: WARNING: connectionpool: Retrying (Retry(total=2, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:24:25,752: WARNING: connectionpool: Retrying (Retry(total=1, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:28:57,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:28:57,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:28:57,933: INFO: common: created directory at: artifacts]
[2024-02-09 21:29:11,025: INFO: common: json file saved at: scores.json]
[2024-02-09 21:29:15,545: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:29:16,252: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmptb9a8j0v\model\data\model\assets]
[2024-02-09 21:36:00,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:36:00,753: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:36:00,755: INFO: common: created directory at: artifacts]
[2024-02-09 21:36:13,747: INFO: common: json file saved at: scores.json]
[2024-02-09 21:36:18,736: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:36:19,526: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpy5yxb823\model\data\model\assets]
[2024-02-09 21:43:25,646: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/c263475b1fd344f3bf038506c5640f51/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:44:00,771: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/c263475b1fd344f3bf038506c5640f51/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-03-01 19:07:22,793: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:07:22,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:07:22,810: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:07:22,811: INFO: common: created directory at: artifacts]
[2024-03-01 19:07:22,812: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:07:22,813: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:08:15,735: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:08:16,798: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:08:16,798: INFO: main: *******************]
[2024-03-01 19:08:16,798: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:08:16,804: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:08:16,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:08:16,809: INFO: common: created directory at: artifacts]
[2024-03-01 19:08:16,810: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:08:17,864: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:08:18,484: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:08:18,485: INFO: main: *******************]
[2024-03-01 19:08:18,486: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:08:18,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:08:18,496: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:08:18,497: INFO: common: created directory at: artifacts]
[2024-03-01 19:08:18,498: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:09:14,747: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:09:14,747: INFO: main: *******************]
[2024-03-01 19:09:14,747: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:09:14,753: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:09:14,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:09:14,756: INFO: common: created directory at: artifacts]
[2024-03-01 19:09:33,184: INFO: common: json file saved at: scores.json]
[2024-03-01 19:09:33,185: INFO: common: json file saved at: scores.json]
[2024-03-01 19:09:33,186: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:15:55,829: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:15:55,835: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:15:55,851: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:15:55,852: INFO: common: created directory at: artifacts]
[2024-03-01 19:15:55,854: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:15:55,855: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:20:47,614: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:20:48,897: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:20:48,899: INFO: main: *******************]
[2024-03-01 19:20:48,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:20:48,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:20:48,909: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:20:48,910: INFO: common: created directory at: artifacts]
[2024-03-01 19:20:48,911: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:20:50,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:20:50,954: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:20:50,956: INFO: main: *******************]
[2024-03-01 19:20:50,957: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:20:50,961: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:20:50,967: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:20:50,968: INFO: common: created directory at: artifacts]
[2024-03-01 19:20:50,970: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:25:34,788: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:25:34,789: INFO: main: *******************]
[2024-03-01 19:25:34,790: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:25:34,795: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:25:34,801: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:25:34,802: INFO: common: created directory at: artifacts]
[2024-03-01 19:25:52,897: INFO: common: json file saved at: scores.json]
[2024-03-01 19:25:52,898: INFO: common: json file saved at: scores.json]
[2024-03-01 19:25:52,899: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:26:59,219: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:26:59,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:26:59,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:26:59,243: INFO: common: created directory at: artifacts]
[2024-03-01 19:26:59,245: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:26:59,246: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:28:11,635: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:28:12,895: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:28:12,896: INFO: main: *******************]
[2024-03-01 19:28:12,897: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:28:12,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:28:12,909: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:28:12,910: INFO: common: created directory at: artifacts]
[2024-03-01 19:28:12,911: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:28:13,909: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:28:14,463: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:28:14,464: INFO: main: *******************]
[2024-03-01 19:28:14,464: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:28:14,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:28:14,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:28:14,476: INFO: common: created directory at: artifacts]
[2024-03-01 19:28:14,478: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:31:04,656: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:31:04,657: INFO: main: *******************]
[2024-03-01 19:31:04,658: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:31:04,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:31:04,668: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:31:04,669: INFO: common: created directory at: artifacts]
[2024-03-01 19:31:22,690: INFO: common: json file saved at: scores.json]
[2024-03-01 19:31:22,691: INFO: common: json file saved at: scores.json]
[2024-03-01 19:31:22,693: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:40:07,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:40:07,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:40:07,906: INFO: common: created directory at: artifacts]
[2024-03-01 19:40:27,009: INFO: common: json file saved at: scores.json]
[2024-03-01 19:40:33,723: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-01 19:40:35,303: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmprqvjqd3n\model\data\model\assets]
[2024-03-01 20:25:04,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 20:25:04,552: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 20:25:04,554: INFO: common: created directory at: artifacts]
[2024-03-01 20:25:17,919: INFO: common: json file saved at: scores.json]
[2024-03-01 20:25:26,805: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-01 20:25:27,538: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpcysokez1\model\data\model\assets]
[2024-03-01 21:52:24,180: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 21:52:24,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:52:24,196: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:52:24,196: INFO: common: created directory at: artifacts]
[2024-03-01 21:52:24,196: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 21:52:24,212: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 21:54:14,753: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 21:54:15,925: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 21:54:15,925: INFO: main: *******************]
[2024-03-01 21:54:15,925: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 21:54:15,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:54:15,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:54:15,935: INFO: common: created directory at: artifacts]
[2024-03-01 21:54:15,935: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 21:54:16,878: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 21:54:17,236: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 21:54:17,236: INFO: main: *******************]
[2024-03-01 21:54:17,238: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 21:54:17,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:54:17,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:54:17,248: INFO: common: created directory at: artifacts]
[2024-03-01 21:54:17,249: INFO: common: created directory at: artifacts\training]
[2024-03-01 22:03:02,962: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 22:03:02,962: INFO: main: *******************]
[2024-03-01 22:03:02,962: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 22:03:02,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 22:03:02,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 22:03:02,979: INFO: common: created directory at: artifacts]
[2024-03-01 22:03:20,596: INFO: common: json file saved at: scores.json]
[2024-03-01 22:03:20,597: INFO: common: json file saved at: scores.json]
[2024-03-01 22:03:20,599: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-02 11:27:31,302: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-02 11:27:31,305: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:27:31,307: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:27:31,308: INFO: common: created directory at: artifacts]
[2024-03-02 11:27:31,308: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-02 11:27:31,308: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-02 11:28:26,034: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-02 11:28:26,651: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-02 11:28:44,466: INFO: stage_02_prepare_base_model: *******************]
[2024-03-02 11:28:44,467: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-02 11:28:44,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:28:44,472: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:28:44,472: INFO: common: created directory at: artifacts]
[2024-03-02 11:28:44,472: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-02 11:28:45,143: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-02 11:28:45,430: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-02 11:28:52,338: INFO: stage_03_model_training: *******************]
[2024-03-02 11:28:52,339: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-02 11:28:52,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:28:52,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:28:52,345: INFO: common: created directory at: artifacts]
[2024-03-02 11:28:52,346: INFO: common: created directory at: artifacts\training]
[2024-03-02 11:35:49,915: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-02 11:35:58,995: INFO: stage_04_model_evaluation: *******************]
[2024-03-02 11:35:58,996: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-02 11:35:58,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:35:59,000: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:35:59,000: INFO: common: created directory at: artifacts]
[2024-03-02 11:36:13,060: INFO: common: json file saved at: scores.json]
[2024-03-02 11:36:13,061: INFO: common: json file saved at: scores.json]
[2024-03-02 11:36:13,062: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-02 12:33:51,605: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019E14295B40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-02 12:34:05,510: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019E14295AB0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-02 13:59:15,346: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001BD1DD1AE60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:46:35,943: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D706986830> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:46:45,544: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D706985870> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 19:05:34,107: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:05:34,108: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:05:40,000: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:05:40] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:06:15,394: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:06:15] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:07:26,882: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:07:44,166: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:07:44,168: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:07:47,856: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:47] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:07:55,391: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:08:43,276: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:08:43] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:10:56,441: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:10:56,457: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:10:56,461: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:10:56,462: INFO: common: created directory at: artifacts]
[2024-03-08 19:10:56,463: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:10:56,464: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:10:59,794: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:11:32,856: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:11:32,861: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:11:32,868: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:11:32,869: INFO: common: created directory at: artifacts]
[2024-03-08 19:11:32,870: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:11:32,871: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:11:35,425: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:15:00,016: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:15:00,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:15:00,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:15:00,024: INFO: common: created directory at: artifacts]
[2024-03-08 19:15:00,025: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:15:00,025: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:15:03,274: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:16:22,957: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:16:22,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:16:22,962: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:16:22,963: INFO: common: created directory at: artifacts]
[2024-03-08 19:16:22,963: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:16:22,963: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:16:25,141: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:17:46,682: INFO: stage_03_model_training: *******************]
[2024-03-08 19:17:46,683: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 19:17:46,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:17:46,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:17:46,688: INFO: common: created directory at: artifacts]
[2024-03-08 19:17:46,689: INFO: common: created directory at: artifacts\training]
[2024-03-08 19:24:42,868: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:24:42,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:24:42,879: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:24:42,880: INFO: common: created directory at: artifacts]
[2024-03-08 19:24:42,880: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:24:42,880: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:24:45,146: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:29:40,519: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:29:40,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:29:40,531: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:29:40,531: INFO: common: created directory at: artifacts]
[2024-03-08 19:29:40,532: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:29:40,532: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17XmTb8SLbzxgia-TaybLFRanEy_xUKBX/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:29:43,533: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=17XmTb8SLbzxgia-TaybLFRanEy_xUKBX

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=17XmTb8SLbzxgia-TaybLFRanEy_xUKBX

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:31:36,023: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:31:36,026: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:31:36,034: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:31:36,035: INFO: common: created directory at: artifacts]
[2024-03-08 19:31:36,035: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:31:36,035: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17XmTb8SLbzxgia-TaybLFRanEy_xUKBX/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:31:37,989: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=17XmTb8SLbzxgia-TaybLFRanEy_xUKBX

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=17XmTb8SLbzxgia-TaybLFRanEy_xUKBX

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:32:40,109: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:32:40,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:32:40,121: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:32:40,121: INFO: common: created directory at: artifacts]
[2024-03-08 19:32:40,122: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:32:40,122: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17XmTb8SLbzxgia-TaybLFRanEy_xUKBX/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:33:35,563: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17XmTb8SLbzxgia-TaybLFRanEy_xUKBX/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:33:36,177: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-08 19:33:36,178: INFO: main: *******************]
[2024-03-08 19:33:36,178: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-08 19:33:36,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:33:36,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:33:36,185: INFO: common: created directory at: artifacts]
[2024-03-08 19:33:36,187: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-08 19:33:36,718: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-08 19:33:37,000: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-08 19:33:37,001: INFO: main: *******************]
[2024-03-08 19:33:37,001: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-08 19:33:37,004: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:33:37,006: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:33:37,006: INFO: common: created directory at: artifacts]
[2024-03-08 19:33:37,007: INFO: common: created directory at: artifacts\training]
[2024-03-08 19:36:52,079: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 19:36:52,080: INFO: main: *******************]
[2024-03-08 19:36:52,080: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 19:36:52,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:36:52,085: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:36:52,086: INFO: common: created directory at: artifacts]
[2024-03-08 19:37:04,890: INFO: common: json file saved at: scores.json]
[2024-03-08 19:37:04,891: INFO: common: json file saved at: scores.json]
[2024-03-08 19:37:04,892: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 19:44:54,713: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:44:54,713: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:44:59,536: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:44:59] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:45:05,684: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:45:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:45:21,010: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:45:21] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:45:53,969: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:45:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:48:05,111: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:48:05] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:51:46,860: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:51:46,861: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:51:50,876: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:51:50] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:51:58,034: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:51:58] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:52:11,985: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:52:11] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:52:20,178: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:52:20] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:18:19,251: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 21:18:19,252: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 21:18:24,924: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:18:24] "GET / HTTP/1.1" 200 -]
[2024-03-08 21:18:38,077: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:18:38] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:18:55,196: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:18:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:19:36,701: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:19:36] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:19:50,257: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:19:50] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:23:57,676: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001F51BCC6DD0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 21:23:57,685: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:23:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:24:08,979: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001F51BCC7520> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 21:24:08,991: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:24:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:24:30,729: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 21:24:30,730: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 21:24:33,646: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:24:33] "GET / HTTP/1.1" 200 -]
[2024-03-08 21:24:41,848: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:24:41] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:25:54,710: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:25:54] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:27:41,300: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:27:41] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:35:05,631: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:35:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:35:58,668: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000232C6036DD0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 21:35:58,678: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:35:58] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 21:36:14,317: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 21:36:14,318: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 21:36:16,707: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:36:16] "GET / HTTP/1.1" 200 -]
[2024-03-08 21:36:25,268: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 21:36:25] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 22:17:21,623: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 22:17:21,623: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 22:17:34,794: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 22:17:34] "GET / HTTP/1.1" 200 -]
[2024-03-08 22:17:42,144: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 22:17:42] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 22:17:55,157: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 22:17:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:09:22,550: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 23:09:22,551: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 23:09:27,467: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:09:27] "GET / HTTP/1.1" 200 -]
[2024-03-08 23:09:34,400: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:09:34] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:09:46,067: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:09:46] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:10:05,201: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:10:13,398: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:13] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:10:29,582: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000146C8F12DD0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 23:10:29,587: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:29] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:10:43,033: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000146C8F13520> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 23:10:43,038: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:43] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:10:48,763: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:48] "GET / HTTP/1.1" 200 -]
[2024-03-08 23:10:54,810: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:10:54] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:11:44,080: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 23:11:44,081: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 23:11:50,230: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:11:50] "GET / HTTP/1.1" 200 -]
[2024-03-08 23:11:57,813: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:11:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:03,918: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:09,900: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:09] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:18,316: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:36,564: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 23:12:36,565: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 23:12:38,180: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:38] "GET / HTTP/1.1" 200 -]
[2024-03-08 23:12:45,244: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:45] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:52,750: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:12:59,335: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:12:59] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 23:13:08,041: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 23:13:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 00:54:03,548: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 00:54:03,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 00:54:03,572: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 00:54:03,573: INFO: common: created directory at: artifacts]
[2024-03-09 00:54:03,574: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 00:54:03,577: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:10:57,613: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:11:21,328: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 01:11:21,329: INFO: main: *******************]
[2024-03-09 01:11:21,329: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-09 01:11:21,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:11:21,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:11:21,336: INFO: common: created directory at: artifacts]
[2024-03-09 01:11:21,337: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-09 01:11:21,834: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-09 01:11:22,103: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-09 01:11:22,105: INFO: main: *******************]
[2024-03-09 01:11:22,105: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-09 01:11:22,107: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:11:22,109: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:11:22,110: INFO: common: created directory at: artifacts]
[2024-03-09 01:11:22,111: INFO: common: created directory at: artifacts\training]
[2024-03-09 01:11:22,485: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    model_trainer.main()
  File "e:\ml project\covid project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "e:\ml project\covid project\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-09 01:15:57,135: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 01:15:57,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:15:57,142: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:15:57,142: INFO: common: created directory at: artifacts]
[2024-03-09 01:15:57,143: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 01:15:57,143: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:17:56,759: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 01:17:56,762: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:17:56,764: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:17:56,764: INFO: common: created directory at: artifacts]
[2024-03-09 01:17:56,764: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 01:17:56,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:34:46,269: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:35:10,361: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 01:39:04,746: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 01:39:04,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:39:04,752: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:39:04,753: INFO: common: created directory at: artifacts]
[2024-03-09 01:39:04,755: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 01:39:04,755: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:39:52,630: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 01:39:52,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:39:52,635: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:39:52,635: INFO: common: created directory at: artifacts]
[2024-03-09 01:39:52,637: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 01:39:52,638: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:56:39,200: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 01:57:04,116: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 01:58:57,776: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 01:58:57,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 01:58:57,782: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 01:58:57,782: INFO: common: created directory at: artifacts]
[2024-03-09 01:58:57,783: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 01:58:57,784: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 02:01:28,096: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 02:01:28,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 02:01:28,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 02:01:28,102: INFO: common: created directory at: artifacts]
[2024-03-09 02:01:28,103: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 02:01:28,105: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 02:01:49,784: ERROR: stage_01_data_ingestion: HTTPSConnectionPool(host='drive.usercontent.google.com', port=443): Max retries exceeded with url: /download?id=1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1- (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023EB9884CA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023EB9884CA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.usercontent.google.com', port=443): Max retries exceeded with url: /download?id=1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1- (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023EB9884CA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\covid project\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\covid project\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\gdown\download.py", line 188, in download
    res = sess.get(url, stream=True, verify=verify)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.usercontent.google.com', port=443): Max retries exceeded with url: /download?id=1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1- (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023EB9884CA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
[2024-03-09 02:02:03,554: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 02:02:03,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 02:02:03,559: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 02:02:03,561: INFO: common: created directory at: artifacts]
[2024-03-09 02:02:03,561: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 02:02:03,562: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 02:18:46,992: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 02:20:00,738: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 11:26:46,726: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 11:26:46,733: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 11:26:46,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 11:26:46,740: INFO: common: created directory at: artifacts]
[2024-03-09 11:26:46,741: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 11:26:46,742: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 11:26:49,044: ERROR: stage_01_data_ingestion: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\covid project\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\covid project\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\covid\lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1GnUk41NLMEoXdJk2eWAbcYczGmz0mJ1-

but Gdown can't. Please check connections and permissions.
[2024-03-09 12:33:53,567: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 12:33:53,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 12:33:53,600: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 12:33:53,603: INFO: common: created directory at: artifacts]
[2024-03-09 12:33:53,605: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 12:33:53,606: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1BWlyuJsl7duQNZsp64oQGpDK4b29_sfj/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 12:52:02,836: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1BWlyuJsl7duQNZsp64oQGpDK4b29_sfj/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 12:52:44,707: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 13:17:48,768: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 13:17:48,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 13:17:48,774: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 13:17:48,775: INFO: common: created directory at: artifacts]
[2024-03-09 13:17:48,775: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 13:17:48,776: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1oGhLTYxyvZ-oNLibgOuizzbk2IXWM35B/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 13:37:25,587: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1oGhLTYxyvZ-oNLibgOuizzbk2IXWM35B/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 13:37:45,304: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 13:48:07,787: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 13:48:07,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 13:48:07,793: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 13:48:07,794: INFO: common: created directory at: artifacts]
[2024-03-09 13:48:07,795: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 13:48:07,796: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1oGhLTYxyvZ-oNLibgOuizzbk2IXWM35B/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 14:10:15,187: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-09 14:10:15,191: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 14:10:15,194: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 14:10:15,194: INFO: common: created directory at: artifacts]
[2024-03-09 14:10:15,195: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-09 14:10:15,196: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/10FxHfJe2vXdK2wo8UAzbHaAhXCjO3b_W/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 14:28:51,363: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/10FxHfJe2vXdK2wo8UAzbHaAhXCjO3b_W/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-09 14:29:32,105: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-09 14:39:27,949: INFO: stage_02_prepare_base_model: *******************]
[2024-03-09 14:39:27,950: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-09 14:39:27,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 14:39:27,960: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 14:39:27,961: INFO: common: created directory at: artifacts]
[2024-03-09 14:39:27,962: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-09 14:39:29,555: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-09 14:39:30,216: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-09 14:40:16,844: INFO: stage_03_model_training: *******************]
[2024-03-09 14:40:16,845: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-09 14:40:16,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-09 14:40:16,870: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-09 14:40:16,874: INFO: common: created directory at: artifacts]
[2024-03-09 14:40:16,878: INFO: common: created directory at: artifacts\training]
